#Lenguaje usado
language: python
python:
    - "2.7"
#Instalar dependencias
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install pep8
    - pip install radon
script:
    - pep8 src/.
    - pep8 test/.
    - radon cc src/.
    - radon mi src/.
    - radon raw src/.
    - radon cc test/.
    - radon mi test/.
    - radon raw test/.