#Lenguaje usado
language: python
python:
    - "2.7"
#Instalar dependencias
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install pep8
    - pip install radon
script:
    - pep8 src/.
    - pep8 tests/.
    - radon cc src/.
    - radon mi src/.
    - radon raw src/.
    - radon cc tests/.
    - radon mi tests/.
    - radon raw tests/.
    - py.test --cov . --cov-report term-missing
after_success:
    - coveralls
notifications:
    email:
        recipients:
            - fj.moron@gmail.com
        on_failure: always