#Lenguaje usado
language: python
python:
    - "2.7"
#Instalar dependencias
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install pep8
    - pip install radon
